/// IPC bridge between the Tauri app and the sentinel daemon.
///
/// The daemon listens on a Unix socket (macOS/Linux) or named pipe (Windows).
/// This module:
///   1. Connects to the daemon socket on startup.
///   2. Exposes `ipc_send` as a Tauri command so the React frontend can send
///      messages and receive typed responses.
///   3. Forwards unsolicited daemon broadcasts to the frontend via Tauri events.
///
/// Request/response correlation: `ipc_send` registers a oneshot channel keyed
/// by `requestType`. When the read loop in `connect_daemon` receives a response
/// it delivers it to the waiting command, then also emits a Tauri event so
/// unsolicited broadcasts (overage_entered, etc.) still reach the frontend.
use std::collections::{HashMap, VecDeque};
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::sync::{oneshot, Mutex};

#[cfg(windows)]
use tokio::net::windows::named_pipe::{ClientOptions, NamedPipeClient};
#[cfg(unix)]
use tokio::net::UnixStream;

#[cfg(unix)]
type DaemonStream = UnixStream;
#[cfg(windows)]
type DaemonStream = NamedPipeClient;

/// Shared write-half of the daemon socket/pipe, protected by a mutex.
static DAEMON_SOCKET: Mutex<Option<tokio::io::WriteHalf<DaemonStream>>> = Mutex::const_new(None);

/// Pending request/response correlations keyed by `requestType`.
///
/// A FIFO queue per type, not a single slot — the daemon's response
/// protocol uses the message `type` as the correlation key, but nothing
/// about that mandates "only one in flight per type". Two components
/// calling `sendToSentinel({type:'get_rate_limits'})` concurrently is
/// entirely legitimate (e.g., UsageView and AccountSwitcher both
/// refreshing on mount). Without a queue, the second `insert` would
/// replace the first Sender and the first caller's Receiver would raise
/// "Response channel dropped" (see send_internal's mapping below).
///
/// The daemon processes messages on the socket in order (single async
/// read loop in `packages/daemon/src/ipc.ts`), so responses for the same
/// type come back in the order the requests were sent. Pop from the
/// front on response delivery.
static PENDING: LazyLock<Mutex<HashMap<String, VecDeque<oneshot::Sender<serde_json::Value>>>>> =
    LazyLock::new(|| Mutex::new(HashMap::new()));

#[cfg(unix)]
async fn connect_stream() -> std::io::Result<DaemonStream> {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
    let path = std::path::PathBuf::from(home)
        .join(".claude-sentinel")
        .join("daemon.sock");
    UnixStream::connect(&path).await
}

#[cfg(windows)]
async fn connect_stream() -> std::io::Result<DaemonStream> {
    ClientOptions::new().open(r"\\.\pipe\claude-sentinel")
}

/// Connect to the daemon socket and forward incoming messages to the frontend.
/// Retries with back-off if the daemon is not yet running.
pub async fn connect_daemon(app: AppHandle) {
    let mut backoff_ms = 500u64;

    loop {
        match connect_stream().await {
            Ok(stream) => {
                backoff_ms = 500;
                let (reader, mut writer) = tokio::io::split(stream);

                // Sprint 2 handshake: every connection's first line must
                // be `{type:"_handshake", token:"<hex>"}` or the daemon
                // closes the socket. The token was generated by `daemon::
                // spawn` and stashed in `IPC_HANDSHAKE_TOKEN` before the
                // daemon was launched. If the token is somehow missing —
                // shouldn't happen because spawn populates it before we
                // start retrying — we skip the handshake; the daemon
                // will reject us and we'll loop into another retry.
                if let Some(token) = crate::daemon::IPC_HANDSHAKE_TOKEN.get() {
                    let handshake = serde_json::json!({ "type": "_handshake", "token": token });
                    let mut line = handshake.to_string();
                    line.push('\n');
                    if let Err(e) = writer.write_all(line.as_bytes()).await {
                        eprintln!("[sentinel] Failed to send IPC handshake: {e}");
                        // Treat as a failed connection — drop the writer
                        // and reconnect on the next loop iteration. The
                        // daemon's IPC server will see a half-open socket
                        // and clean up.
                        tokio::time::sleep(tokio::time::Duration::from_millis(backoff_ms)).await;
                        backoff_ms = (backoff_ms * 2).min(10_000);
                        continue;
                    }
                }

                // Store the writer for outbound messages
                {
                    let mut guard = DAEMON_SOCKET.lock().await;
                    *guard = Some(writer);
                }

                // Read loop: deliver responses to pending requests, and also
                // emit every message as a Tauri event for unsolicited broadcasts.
                let mut lines = BufReader::new(reader).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    if line.trim().is_empty() {
                        continue;
                    }
                    if let Ok(value) = serde_json::from_str::<serde_json::Value>(&line) {
                        // Resolve the oldest pending ipc_send call for this
                        // requestType. The daemon's FIFO ordering on the
                        // socket means the front of the queue is always the
                        // one this response belongs to. When the queue
                        // empties, remove the entry to bound memory.
                        if let Some(req_type) = value
                            .get("requestType")
                            .and_then(|v| v.as_str())
                            .map(str::to_owned)
                        {
                            let mut pending = PENDING.lock().await;
                            if let Some(queue) = pending.get_mut(&req_type) {
                                if let Some(tx) = queue.pop_front() {
                                    let _ = tx.send(value.clone());
                                }
                                if queue.is_empty() {
                                    pending.remove(&req_type);
                                }
                            }
                        }
                        // Always forward to frontend for broadcasts
                        let _ = app.emit("daemon-message", value.clone());

                        // Drive the dynamic tray icon. Spawned in a separate
                        // task so the handler can issue its own send_internal
                        // calls (which need this same read loop to deliver
                        // their responses) without blocking us here.
                        let app_for_tray = app.clone();
                        tauri::async_runtime::spawn(async move {
                            crate::tray::handle_daemon_message(value, app_for_tray).await;
                        });
                    }
                }

                // Socket closed — clear the writer and reconnect.
                {
                    let mut guard = DAEMON_SOCKET.lock().await;
                    *guard = None;
                }
                // Drain PENDING. Any senders whose write went out on the
                // now-dead socket will never get a response; leaving them
                // in place orphans them at the front of each FIFO queue,
                // which eats subsequent real responses and deadlocks every
                // future call of the same request_type until the app is
                // restarted. Clearing lets callers see their oneshot
                // Receiver drop ("Response channel dropped") and retry
                // cleanly against the new connection.
                {
                    let mut pending = PENDING.lock().await;
                    pending.clear();
                }
            }
            Err(_) => {
                tokio::time::sleep(tokio::time::Duration::from_millis(backoff_ms)).await;
                backoff_ms = (backoff_ms * 2).min(10_000);
            }
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct IpcResponse {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "requestType")]
    pub request_type: String,
}

/// Send a JSON message to the daemon and wait for the typed response.
///
/// Registers a oneshot channel keyed by the message's `type` field, sends the
/// message, then awaits the channel with a 5-second timeout. The read loop in
/// `connect_daemon` delivers the daemon's reply to the channel.
///
/// Callable from Rust (e.g. tray seeding); the `ipc_send` Tauri command
/// below delegates here so frontend and Rust share one code path.
pub async fn send_internal(message: serde_json::Value) -> Result<IpcResponse, String> {
    let request_type = message
        .get("type")
        .and_then(|t| t.as_str())
        .unwrap_or("unknown")
        .to_string();

    let (tx, rx) = oneshot::channel::<serde_json::Value>();

    // Register the sender BEFORE writing so the read loop never finds an
    // empty queue when a racing response comes back — FIFO correlation by
    // request_type depends on this ordering.
    {
        let mut pending = PENDING.lock().await;
        pending
            .entry(request_type.clone())
            .or_default()
            .push_back(tx);
    }

    // Send the message to the daemon. If the write fails we must un-push
    // the sender we just registered; otherwise it sits in the queue
    // forever, gets popped by a later response that belongs to someone
    // else, and silently swallows it (the caller then times out at 5s).
    let write_result: Result<(), String> = async {
        let mut guard = DAEMON_SOCKET.lock().await;
        let writer = guard
            .as_mut()
            .ok_or_else(|| "Daemon not connected".to_string())?;
        let mut line = serde_json::to_string(&message).map_err(|e| e.to_string())?;
        line.push('\n');
        writer
            .write_all(line.as_bytes())
            .await
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    .await;

    if let Err(e) = write_result {
        let mut pending = PENDING.lock().await;
        if let Some(queue) = pending.get_mut(&request_type) {
            // pop_back removes the sender most recently pushed, which is
            // ours under normal conditions. A concurrent caller racing in
            // between our push and the failed write would also be failing
            // (same dead socket), so if we pop theirs by accident their
            // own failure path removes ours — net result: both senders
            // drop, both callers see an error, queue stays consistent.
            queue.pop_back();
            if queue.is_empty() {
                pending.remove(&request_type);
            }
        }
        return Err(e);
    }

    // Wait for the daemon's response. Default 5s is comfortable for every
    // routine IPC; `run_scan_benchmark` runs a real CPU-bound benchmark
    // (5 sizes × up to 2000ms cap apiece) that legitimately exceeds the
    // 5s budget on M-series chips under thermal load or cold caches, so
    // it gets a 30s window. New long-running handlers should be added
    // here explicitly rather than raising the default for everyone.
    let timeout_secs = if request_type == "run_scan_benchmark" {
        30
    } else {
        5
    };
    match tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), rx).await {
        Ok(Ok(value)) => serde_json::from_value::<IpcResponse>(value).map_err(|e| e.to_string()),
        Ok(Err(_)) => Err("Response channel dropped".to_string()),
        Err(_) => {
            // On timeout we DON'T try to remove our specific Sender from
            // the VecDeque — we have no way to identify it without adding
            // per-call IDs, and arbitrary removal would misalign FIFO
            // delivery. Instead, we let the Sender stay in the queue; our
            // `rx` is already dropped so when the daemon's (late) response
            // eventually arrives, the read loop pops the stale Sender,
            // calls `tx.send(..)`, and the value is dropped harmlessly
            // (Receiver is gone). Total overhead: one dead slot in the
            // queue, cleared on the next matching response.
            Err(format!(
                "Timeout waiting for daemon response to '{request_type}'"
            ))
        }
    }
}

/// Tauri command form of `send_internal` — exposed to the React frontend.
#[tauri::command]
pub async fn ipc_send(message: serde_json::Value) -> Result<IpcResponse, String> {
    send_internal(message).await
}

/// True when the daemon socket has been established.
pub async fn is_connected() -> bool {
    DAEMON_SOCKET.lock().await.is_some()
}
