/**
 * Sprint 2 anti-tamper: IPC handshake-token enforcement.
 *
 * The daemon's IPC server demands a `{type:'_handshake', token:'<hex>'}`
 * message as the first complete line on every new connection. The token
 * is generated by the Tauri parent at spawn time and shared with the
 * daemon over its stdin pipe; the legitimate `IpcClient` sends the same
 * token automatically on connect. Any other peer (a Bash agent piping
 * directly into `~/.sentinel/daemon.sock`) is dropped before its
 * second line is read.
 *
 * The bypass via `SENTINEL_TEST_IPC_TOKEN` exists for legacy
 * integration tests that don't go through the Tauri parent. We exercise
 * it here too so the default-allow-on-bypass branch is covered.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { connect } from 'net';
import { join } from 'path';
import { tmpdir } from 'os';
import { existsSync, unlinkSync } from 'fs';
import { IpcServer, IpcClient, HANDSHAKE_MSG_TYPE } from './ipc.js';

const VALID_TOKEN = 'a'.repeat(64); // 32-byte hex
const WRONG_TOKEN = 'b'.repeat(64);

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function uniqueSock(): string {
  return join(
    tmpdir(),
    `sentinel-peer-auth-${Date.now()}-${Math.random().toString(36).slice(2)}.sock`,
  );
}

describe('IpcServer handshake', () => {
  let server: IpcServer;
  let sock: string;
  let warnSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    server = new IpcServer();
    sock = uniqueSock();
    delete process.env.SENTINEL_TEST_IPC_TOKEN;
    warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    server.close();
    if (existsSync(sock)) unlinkSync(sock);
    warnSpy.mockRestore();
  });

  it('drops a connection that sends no handshake at all', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg) => messages.push(msg));

    // Connect raw and send a normal message as the first line — should
    // be rejected before reaching the handler.
    const raw = connect(sock);
    await new Promise<void>((resolve) => raw.once('connect', () => resolve()));
    raw.write(JSON.stringify({ type: 'get_accounts' }) + '\n');
    await sleep(80);

    expect(messages).toHaveLength(0);
    expect(server.connectedClients).toBe(0);
    expect(warnSpy).toHaveBeenCalled();
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('Rejected'))).toBe(true);
    raw.destroy();
  });

  it('drops a connection whose handshake type is wrong', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg) => messages.push(msg));

    const raw = connect(sock);
    await new Promise<void>((resolve) => raw.once('connect', () => resolve()));
    raw.write(JSON.stringify({ type: 'wrong_type', token: VALID_TOKEN }) + '\n');
    await sleep(80);

    expect(messages).toHaveLength(0);
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('first message type'))).toBe(true);
    raw.destroy();
  });

  it('drops a connection whose handshake first line is malformed JSON', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg) => messages.push(msg));

    const raw = connect(sock);
    await new Promise<void>((resolve) => raw.once('connect', () => resolve()));
    raw.write('not-json-at-all\n');
    await sleep(80);

    expect(messages).toHaveLength(0);
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('malformed first line'))).toBe(
      true,
    );
    raw.destroy();
  });

  it('drops a connection whose handshake token is wrong', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg) => messages.push(msg));

    const raw = connect(sock);
    await new Promise<void>((resolve) => raw.once('connect', () => resolve()));
    raw.write(JSON.stringify({ type: HANDSHAKE_MSG_TYPE, token: WRONG_TOKEN }) + '\n');
    raw.write(JSON.stringify({ type: 'get_accounts' }) + '\n');
    await sleep(80);

    expect(messages).toHaveLength(0);
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('token mismatch'))).toBe(true);
    raw.destroy();
  });

  it('drops a connection whose handshake first line is not an object', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg) => messages.push(msg));

    const raw = connect(sock);
    await new Promise<void>((resolve) => raw.once('connect', () => resolve()));
    raw.write('"a string"\n');
    await sleep(80);

    expect(messages).toHaveLength(0);
    expect(
      warnSpy.mock.calls.some((c) => String(c[0]).includes('first line was not an object')),
    ).toBe(true);
    raw.destroy();
  });

  it('accepts a handshake with the correct token and routes subsequent messages', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg, respond) => {
      messages.push(msg);
      respond({ requestType: msg.type, success: true });
    });

    const client = new IpcClient();
    client.connect(sock, VALID_TOKEN);
    await sleep(80);

    client.send({ type: 'get_accounts' });
    await sleep(80);

    expect(messages).toHaveLength(1);
    expect((messages[0] as { type: string }).type).toBe('get_accounts');
    expect(server.connectedClients).toBe(1);
    expect(warnSpy).not.toHaveBeenCalled();
    client.close();
  });

  it('two valid connections both work and the client count reflects both', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const a = new IpcClient();
    const b = new IpcClient();
    a.connect(sock, VALID_TOKEN);
    b.connect(sock, VALID_TOKEN);
    await sleep(80);

    expect(server.connectedClients).toBe(2);
    a.close();
    b.close();
  });

  it('SENTINEL_TEST_IPC_TOKEN env bypasses the handshake check', async () => {
    process.env.SENTINEL_TEST_IPC_TOKEN = '';
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg, respond) => {
      messages.push(msg);
      respond({ requestType: msg.type, success: true });
    });

    // Old-style client without a token — would normally be rejected.
    const client = new IpcClient();
    client.connect(sock);
    await sleep(50);
    client.send({ type: 'get_accounts' });
    await sleep(80);

    expect(messages).toHaveLength(1);
    client.close();
  });

  it('null expectedToken (dev-mode start) accepts any first message', async () => {
    server.start(sock, null);
    await sleep(50);

    const messages: unknown[] = [];
    server.onMessage((msg, respond) => {
      messages.push(msg);
      respond({ requestType: msg.type, success: true });
    });

    const client = new IpcClient();
    client.connect(sock); // no token
    await sleep(50);
    client.send({ type: 'get_accounts' });
    await sleep(80);

    expect(messages).toHaveLength(1);
    client.close();
  });

  it('broadcasts go only to authenticated peers', async () => {
    server.start(sock, VALID_TOKEN);
    await sleep(50);

    const goodMessages: unknown[] = [];
    const good = new IpcClient();
    good.onMessage((msg) => goodMessages.push(msg));
    good.connect(sock, VALID_TOKEN);

    // Bad peer connects raw, never sends handshake — broadcast must
    // not reach it. We can't directly observe its receive buffer, but
    // we can verify connectedClients excludes it after rejection.
    const bad = connect(sock);
    await new Promise<void>((resolve) => bad.once('connect', () => resolve()));
    bad.write(JSON.stringify({ type: 'get_accounts' }) + '\n');
    await sleep(80);

    server.broadcast({ type: 'overage_exited', accountId: 'acc-1' });
    await sleep(50);

    expect(goodMessages).toHaveLength(1);
    expect(server.connectedClients).toBe(1); // only the good one
    bad.destroy();
    good.close();
  });
});
